weather_app/weather_app/weather/urls.py
from django.urls import include, path
from . import views

app_name='weather'
urlpatterns = [
    path('', views.index, name='weather_data'),
    path('add/', views.add, name='add'),
    path(r'^delete/(?P<pk>[0-9]+)/$', views.delete, name='weather_delete'),
    path('accounts/', include('django.contrib.auth.urls'))
]

weather_app/weather_app/weather/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class City(models.Model):
    name = models.CharField(max_length=25)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self): #see city chosen by user
        return self.name

    def setName(self, aName):
        self.name = aName
    
    def printName(self):
        print(self.name)
    class Meta: #show the plural of city as cities instead of citys
        verbose_name_plural = 'cities'

weather_app/weather_app/weather/forms.py
from django.forms import ModelForm, TextInput
from .models import City

class CityForm(ModelForm):
    class Meta:
        model = City
        fields = ['name']
        widgets = {
            'name': TextInput(attrs={'class': 'input', 'placeholder': 'City Name'})
        } #update input class to use the CSS properly

weather_app/weather_app/weather/views.py
from django.shortcuts import render, get_object_or_404, redirect
import requests
from .models import City
from .forms import CityForm
from . import match_clothing
import geoip2.database
from django.views import generic
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
city_data = []

def index(request,localle_escape=False):
    template_name = 'weather/index.html'
    context_object_name = 'weather_data'
    # API
    url = 'http://api.openweathermap.org/data/2.5/weather?q={}&units=imperial&appid=60191ca9e0dc4470867884ba38fd64d8'
    # cities = City.objects.all() # return all cities in db
    cityName = 'Normal'
    form = None
    cur_url = reverse('weather:weather_data')

    cities = City.objects.all() 
    city_data = []
    for city in cities:
        city_data.append(city)
        print(city)
    print("City data" ,city_data)
    if not localle_escape:
        try:
            # get location from ip
            # src https://stackoverflow.com/questions/2218093/django-retrieve-ip-location 
            g = geoip2.database.Reader('../../geoip/GeoLite2-City.mmdb')
            x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
            ip = None
            if x_forwarded_for:
                ip = x_forwarded_for.split(',')[0]
            else:
                ip = request.META.get('REMOTE_ADDR')
            if ip:
                if ip=='127.0.0.1':
                    print("Can't find a location from a localhost, dummy")
                    cityName = g.city('69.174.155.10')
                else:
                    cityName = g.city(ip)
                    print("Successfully acquired location from IP")
            
        except:
            pass
        
        if request.method == 'POST' and 'delete' not in request.POST:
            form = CityForm(request.POST)
            cityName = request.POST.get('name', False)
            form.save
        if request.method == 'GET':
            print('Gotten')
            print(request.GET.get('name', False))
            form = CityForm(request.GET)
            cityName = request.GET.get('name', False)
            if cityName == False:
                cityName = 'Normal'
            form.save
        form = CityForm()

        if request.method == 'POST' and 'delete' in request.POST:
            print('Deleted')
            print(request.POST.get('name', False))
            City.objects.filter(pk=request.POST.get('name', False)).delete()
            return HttpResponseRedirect(request.path)
            
    # Request API data and convert to json type
    city = requests.get(url.format(cityName)).json()
    clothStr = None
    try:
        lon = city['coord']['lon']
        lat = city['coord']['lat']
        # print(city)
        url = 'http://api.openweathermap.org/geo/1.0/reverse?lat={}&lon={}&limit=5&appid=60191ca9e0dc4470867884ba38fd64d8'
        location = requests.get(url.format(lat, lon)).json()
        state = location[0]['state']
        print("Location: ", state)
        # dictionary that stores weather data retrieved by user
        weather = {
            'city': city['name'] + ', ' + state,
            'temperature': city['main']['temp'],
            'description': city['weather'][0]['description'],
            'icon': city['weather'][0]['icon'],
            'feels like': city['main']['feels_like'],
            'humidity': city['main']['humidity']
        }
        clothStr = match_clothing.get_clothing(weather.get('temperature'), 'F', weather.get('feels like'), weather.get('humidity'))
    except:
        print("City not found")
        # weather = {
        #     'city': 'DEFAULT',
        #     'state': 'DEFAULT',
        #     'temperature': '70',
        #     'description': 'DEFAULT',
        #     'icon': 'DEFAULT',
        #     'feels like':'70',
        #     'humidity':'50'
        # }
        # clothStr = ''
        return index(request,localle_escape=True)
        
    context = {'weather': weather, 'form': form,'cloth':clothStr, 'city_data': city_data, 'pname':cur_url}
    return render(request, 'weather/index.html', context) # returns the index.html template

def add(request):
    print('User:' ,request.user)
    form = CityForm(request.POST)
    if form.is_valid():
        obj = City()
        obj.author = request.user
        obj.name = request.POST['name']
        obj.save()
    # form.author = request.user
    # form = City.objects.get(name=request.POST['name'], author=request.user)
    # form.save()


    return redirect('weather:weather_data')

    #return redirect('weather:add') OR return render(request, 'weather/index.html', context) however, you need to figure out what context will be equal to
    # OR you might not need to return or redirect anything since it's on the same page. We probably just need to refresh the page

def delete(request, pk):
    form = get_object_or_404(City, pk=pk)
    if request.method == 'POST':
        form.delete()
        return redirect('/')


    return redirect('/')
    

weather_app/weather_app/weather/templates/weather/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>What's the weather like?</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
</head>
<body>
  <header>
    <label  id="dark-change"></label>
  </header>
</head>
</body>
<body class="parent-container d-flex" onload="rectifyUrl();">
    <div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 20%; height: 100vh; background-color: blue;">
        <div class="row">
            <div class="col-xs-4 p-2">
                <h3>Saved Cities</h3>
                <form method="POST" action="{% url 'weather:add' %}">
                {% csrf_token %}
                <div class="control is-expanded">
                    {{ form.name }}
                </div>
                <!-- <input placeholder="Add city"> -->
                <button type="submit">Add</button>
                </form>
                <br><br>
                <form method="POST">
                    {% for city in city_data %}
                    <li name="name"> <a href="?name={{ city }}" style="color: aquamarine; line-height: 25pt;" name="name">{{ city }}</a> 
                        <span style="float: right;">
                            <form action="{% url 'weather:weather_delete' city.id %}" method="POST">
                                {% csrf_token %}
                                <input type="submit" value="Delete" style="float: left; margin: 0; text-align:right; background-color: red; color: white; border: white;">
                            </form>
                        </span>
                    </li>
                    {% endfor %}
                <!-- <ul>
                    <li><button style="background-color: red;">X</button>      <a href="" style="color: aquamarine;"><u>City 1</u></a></li>
                    <li><button style="background-color: red;">X</button>      <a href="" style="color: aquamarine;"><u>City 2</u></a></li>
                    <li><button style="background-color: red;">X</button>      <a href="" style="color: aquamarine;"><u>City 3</u></a></li>
                </ul> -->
            </div>
            <script>
       var content = document.getElementsByTagName('body')[0];
       var darkMode = document.getElementById('dark-change');
       darkMode.addEventListener('click', function(){
           darkMode.classList.toggle('active');
           content.classList.toggle('night');
       })
   </script>
        </div>
    </div>
    <div class="d-flex flex-column flex-shrink-0 p-3" style="width: 100%; height: 100vh;">
        <div class="row">
            <div class="d-flex flex-column flex-shrink-0 p-3" style="width: 80%; height: 100vh;">
                <section class="hero is-primary">
                    <div class="hero-body">
                        <div class="container"  style="background-color: #343a40; height: 60px;">
                          <style>
                              body{
                                margin: 0;
                                padding: 0;
                                font-family: sans-serif;
                              }
                              main{
                                margin: 5vh 15%;
                              }
                              h1{
                                font-size: 40px;
                                font-weight: 400;
                                text-align: center;
                              }
                              img{
                                width:50%;
                                height:auto;
                              }
                              p{
                                text-align: justify;
                                font-size: 18px;
                              }
                              label{
                                  position: absolute;
                                  width: 45px;
                                  height: 22px;
                                  right: 20px;
                                  top: 40px;
                                  border: 2px solid;
                                  border-radius: 20px;
                              }
                              label:before{
                                  position: absolute;
                                  content: '';
                                  width:20px;
                                  height: 22px;
                                  left: -2px;
                                  top: -2px;
                                  border-radius: 50%;
                                  background: #000;
                                  cursor: pointer;
                                  transition: 0.4s;
                              }
                              label.active:before{
                                  left: 24px;
                                  background: #fff;
                              }
                              body.night{
                                  background: #000;
                                  color: #fff;
                              }
                              @media screen and (min-width:900px) {
                                .respon{
                                  display: flex;
                                }
                                img{
                                  height:50%;
                                  width:auto;
                                  padding-top: 3vh;
                                  padding-right: 5%;
                                }
                                p{
                                  max-width: 80%;
                                  line-height: 30px;
                                }
                              }
                          </style>
                            <h1 class="title" style="color: white; text-align: center;">
                                What should you wear given the weather?
                            </h1>
                        </div>
                    </div>
                </section>
                <section class="section">
                    <div class="container">
                        <div class="columns">
                            <div class="column is-offset-4 is-4">
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="field has-addons" style="text-align: center;">
                                            <br>
                                            <input placeholder="City Name" name="name">
                                            <button class="button is-info">
                                                Find City
                                            </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </section>
                <section class="section">
                    <div class="container">
                            <div class="column">
                                    <br><br>
                                    <article class="media" style="background-color: aquamarine;">
                                        <div class="media-left p-2">
                                            <figure class="image is-50x50">
                                                <img src="http://openweathermap.org/img/w/{{ weather.icon }}.png" alt="Image">
                                            </figure>
                                        </div>
                                        <div class="media-content">
                                            <div class="content p-2">
                                                <!-- {% for weather in city_data %}
                                                <li>{{ weather }}</li>
                                                {% endfor %} -->
                                                <p>
                                                    <b><span class="title" style="font-size: 27px;">{{ weather.city }}</span><br><br>
                                                    Current Weather:</b><br><span class="subtitle">{{ weather.temperature }}° F</span>
                                                    {{ weather.description }}
                                        <br><br><b>Clothing Reccomendation:</b><br> <span> {{ cloth }}</span>
                                                </p>
                                            </div>
                                        </div>
                                    </article>
                            </div>
                    </div>
                </section>
                <footer class="footer">
                </footer>
            </div>
        </div>
    </div>
    <script>
    		function rectifyUrl() {
			url = "{{ pname }}";
			window.history.pushState("s","",url);
            }
    </script>
</body>
</html>